    <script src="<?= base_url()?>assets/js/jquery.min.js"></script>
    <script src="<?= base_url()?>assets/js/bootstrap.bundle.min.js"></script>
    <script src="<?= base_url()?>assets/js/owl.carousel.min.js"></script>
    <script src="<?= base_url()?>assets/js/waypoints.min.js"></script>
    <script src="<?= base_url()?>assets/js/jquery.counterup.min.js"></script>
    <script src="<?= base_url()?>assets/js/TweenMax.min.js"></script>
    <script src="<?= base_url()?>assets/js/wow.js"></script>
    <script src="<?= base_url()?>assets/js/jquery.magnific-popup.min.js"></script>
    <script src="<?= base_url()?>assets/js/countdown.min.js"></script>
    <script src="<?= base_url()?>assets/js/vegas.min.js"></script>
    <script src="<?= base_url()?>assets/js/theme.js"></script>